[pytest]
testpaths = tests
filterwarnings =
    ignore:Version 0.22.0.*:FutureWarning
    ignore:datetime.datetime.utcnow.*:DeprecationWarning
    ignore:datetime.datetime.utcfromtimestamp.*:DeprecationWarning
    ignore:The `resolve_connection` function is deprecated.*:DeprecationWarning
