"""DVR channel editor tables

Revision ID: 0d816daf3ec3
Revises: f943111a60ed
Create Date: 2026-08-31 18:02:27.262873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d816daf3ec3'
down_revision = 'f943111a60ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dvr_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('include_movies', sa.Boolean(), nullable=False),
    sa.Column('include_tv', sa.Boolean(), nullable=False),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('network_country', sa.String(length=16), nullable=True),
    sa.Column('title_pins', sa.Text(), nullable=True),
    sa.Column('criterion_only', sa.Boolean(), nullable=False),
    sa.Column('leaving_only', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('dvr_channel_series',
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['dvr_channel.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['tv_series.id'], )
    )
    op.create_table('dvr_channel_movies',
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['dvr_channel.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dvr_channel_movies')
    op.drop_table('dvr_channel_series')
    op.drop_table('dvr_channel')
    # ### end Alembic commands ###
