"""empty message

Revision ID: 270a93cff2f8
Revises: 365fc2fbc722
Create Date: 2023-05-18 13:43:07.336236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '270a93cff2f8'
down_revision = '365fc2fbc722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_audio_track', sa.Column('compression_mode', sa.String(length=64), nullable=True))
    op.drop_column('file_subtitle_track', 'compression_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_subtitle_track', sa.Column('compression_mode', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('file_audio_track', 'compression_mode')
    # ### end Alembic commands ###
