"""empty message

Revision ID: 2905816a7b5c
Revises: 270a93cff2f8
Create Date: 2023-12-20 21:15:12.190552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2905816a7b5c'
down_revision = '270a93cff2f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('filesize_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'filesize_bytes')
    # ### end Alembic commands ###
