"""Initial DDL

Revision ID: 2b45991751fb
Revises:
Create Date: 2020-09-16 16:54:12.331483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b45991751fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('imdb_id', sa.String(length=16), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_adult', sa.Boolean(), nullable=True),
    sa.Column('tmdb_backdrop_path', sa.String(length=64), nullable=True),
    sa.Column('tmdb_budget', sa.Integer(), nullable=True),
    sa.Column('tmdb_homepage', sa.String(length=128), nullable=True),
    sa.Column('tmdb_original_language', sa.String(length=16), nullable=True),
    sa.Column('tmdb_original_title', sa.String(length=256), nullable=True),
    sa.Column('tmdb_overview', sa.Text(), nullable=True),
    sa.Column('tmdb_popularity', sa.Float(), nullable=True),
    sa.Column('tmdb_poster_path', sa.String(length=64), nullable=True),
    sa.Column('tmdb_release_date', sa.DateTime(), nullable=True),
    sa.Column('tmdb_revenue', sa.BigInteger(), nullable=True),
    sa.Column('tmdb_runtime', sa.Integer(), nullable=True),
    sa.Column('tmdb_status', sa.String(length=32), nullable=True),
    sa.Column('tmdb_tagline', sa.String(length=384), nullable=True),
    sa.Column('tmdb_title', sa.String(length=256), nullable=True),
    sa.Column('tmdb_video', sa.Boolean(), nullable=True),
    sa.Column('tmdb_vote_average', sa.Float(), nullable=True),
    sa.Column('tmdb_vote_count', sa.Integer(), nullable=True),
    sa.Column('tmdb_data_as_of', sa.DateTime(), nullable=True),
    sa.Column('criterion_spine_number', sa.Integer(), nullable=True),
    sa.Column('criterion_set_title', sa.String(length=512), nullable=True),
    sa.Column('criterion_in_print', sa.Boolean(), nullable=True),
    sa.Column('criterion_disc_owned', sa.Boolean(), nullable=True),
    sa.Column('criterion_bluray', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'year')
    )
    op.create_index(op.f('ix_movie_date_created'), 'movie', ['date_created'], unique=False)
    op.create_index(op.f('ix_movie_date_updated'), 'movie', ['date_updated'], unique=False)
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.create_index(op.f('ix_movie_year'), 'movie', ['year'], unique=False)
    ref_feature_type = op.create_table('ref_feature_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_type')
    )
    ref_quality = op.create_table('ref_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality_title', sa.String(length=32), nullable=False),
    sa.Column('preference', sa.Integer(), nullable=False),
    sa.Column('physical_media', sa.Boolean(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quality_title')
    )
    ref_tmdb_certification = op.create_table('ref_tmdb_certification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('certification', sa.String(length=32), nullable=True),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'certification')
    )
    op.create_table('tmdb_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('tmdb_profile_path', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmdb_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmdb_keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmdb_movie_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_backdrop_path', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('tmdb_poster_path', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmdb_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_logo_path', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('origin_country', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmdb_production_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=16), nullable=True),
    sa.Column('tmdb_logo_path', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmdb_production_country',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmdb_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('air_date', sa.DateTime(), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tmdb_poster_path', sa.String(length=64), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmdb_spoken_language',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('imdb_id', sa.String(length=16), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_backdrop_path', sa.String(length=64), nullable=True),
    sa.Column('tmdb_first_air_date', sa.DateTime(), nullable=True),
    sa.Column('tmdb_homepage', sa.String(length=128), nullable=True),
    sa.Column('tmdb_in_production', sa.Boolean(), nullable=True),
    sa.Column('tmdb_last_air_date', sa.DateTime(), nullable=True),
    sa.Column('tmdb_name', sa.String(length=256), nullable=True),
    sa.Column('tmdb_number_of_episodes', sa.Integer(), nullable=True),
    sa.Column('tmdb_number_of_seasons', sa.Integer(), nullable=True),
    sa.Column('tmdb_original_language', sa.String(length=16), nullable=True),
    sa.Column('tmdb_original_name', sa.String(length=256), nullable=True),
    sa.Column('tmdb_overview', sa.Text(), nullable=True),
    sa.Column('tmdb_popularity', sa.Float(), nullable=True),
    sa.Column('tmdb_poster_path', sa.String(length=64), nullable=True),
    sa.Column('tmdb_status', sa.String(length=32), nullable=True),
    sa.Column('tmdb_type', sa.String(length=32), nullable=True),
    sa.Column('tmdb_vote_average', sa.Float(), nullable=True),
    sa.Column('tmdb_vote_count', sa.Integer(), nullable=True),
    sa.Column('tmdb_data_as_of', sa.DateTime(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tv_series_date_created'), 'tv_series', ['date_created'], unique=False)
    op.create_index(op.f('ix_tv_series_date_updated'), 'tv_series', ['date_updated'], unique=False)
    op.create_index(op.f('ix_tv_series_title'), 'tv_series', ['title'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('untouched_basename', sa.String(length=255), nullable=True),
    sa.Column('media_library', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('dirname', sa.String(length=255), nullable=False),
    sa.Column('basename', sa.String(length=255), nullable=False),
    sa.Column('plex_title', sa.String(length=230), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('feature_type_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('last_episode', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=219), nullable=True),
    sa.Column('quality_id', sa.Integer(), nullable=True),
    sa.Column('fullscreen', sa.Boolean(), nullable=False),
    sa.Column('crop', sa.String(length=19), nullable=True),
    sa.Column('container', sa.String(length=64), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('codec', sa.String(length=64), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('date_localized', sa.DateTime(), nullable=True),
    sa.Column('date_transcoded', sa.DateTime(), nullable=True),
    sa.Column('date_archived', sa.DateTime(), nullable=True),
    sa.Column('aws_untouched_key', sa.String(length=255), nullable=True),
    sa.Column('aws_untouched_date_uploaded', sa.DateTime(), nullable=True),
    sa.Column('aws_untouched_date_deleted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feature_type_id'], ['ref_feature_type.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['quality_id'], ['ref_quality.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['tv_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_aws_untouched_key'), 'file', ['aws_untouched_key'], unique=False)
    op.create_index(op.f('ix_file_date_added'), 'file', ['date_added'], unique=False)
    op.create_index(op.f('ix_file_date_archived'), 'file', ['date_archived'], unique=False)
    op.create_index(op.f('ix_file_date_localized'), 'file', ['date_localized'], unique=False)
    op.create_index(op.f('ix_file_date_transcoded'), 'file', ['date_transcoded'], unique=False)
    op.create_index(op.f('ix_file_date_updated'), 'file', ['date_updated'], unique=False)
    op.create_index(op.f('ix_file_file_path'), 'file', ['file_path'], unique=True)
    op.create_index(op.f('ix_file_fullscreen'), 'file', ['fullscreen'], unique=False)
    op.create_index(op.f('ix_file_media_library'), 'file', ['media_library'], unique=False)
    op.create_index(op.f('ix_file_plex_title'), 'file', ['plex_title'], unique=False)
    op.create_index(op.f('ix_file_version'), 'file', ['version'], unique=False)
    op.create_table('movie_cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.Column('character', sa.String(length=512), nullable=True),
    sa.Column('billing_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['tmdb_credit.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'credit_id', 'character')
    )
    op.create_table('movie_certifications',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('certification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['certification_id'], ['ref_tmdb_certification.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('movie_collections',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['tmdb_movie_collection.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('movie_crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('job', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['tmdb_credit.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'credit_id', 'department', 'job')
    )
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['tmdb_genre.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('movie_keywords',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['tmdb_keyword.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('movie_production_companies',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['tmdb_production_company.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('movie_production_countries',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['tmdb_production_country.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('movie_spoken_languages',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['tmdb_spoken_language.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('tv_cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.Column('character', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['tmdb_credit.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tv_id', 'credit_id', 'character')
    )
    op.create_table('tv_crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('job', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['tmdb_credit.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tv_id', 'credit_id', 'department', 'job')
    )
    op.create_table('tv_genres',
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['tmdb_genre.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_series.id'], )
    )
    op.create_table('tv_keywords',
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['tmdb_keyword.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_series.id'], )
    )
    op.create_table('tv_networks',
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['tmdb_network.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_series.id'], )
    )
    op.create_table('tv_production_companies',
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['tmdb_production_company.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_series.id'], )
    )
    op.create_table('tv_seasons',
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['tmdb_season.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_series.id'], )
    )
    op.create_table('user_movie_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('modified_rating', sa.Float(), nullable=False),
    sa.Column('whole_stars', sa.Integer(), nullable=False),
    sa.Column('half_stars', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('date_watched', sa.DateTime(), nullable=True),
    sa.Column('date_reviewed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_audio_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('track', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=3), nullable=False),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('channels', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'track')
    )
    op.create_table('file_subtitle_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('track', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=3), nullable=False),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('elements', sa.Integer(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('forced', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'track')
    )
    op.bulk_insert(
        ref_feature_type,
        [
            {"feature_type": "Behind The Scenes"},
            {"feature_type": "Deleted Scenes"},
            {"feature_type": "Featurettes"},
            {"feature_type": "Interviews"},
            {"feature_type": "Scenes"},
            {"feature_type": "Shorts"},
            {"feature_type": "Trailers"},
        ],
    )
    op.bulk_insert(
        ref_quality,
        [
            {"quality_title": "Unknown", "preference": "0", "physical_media": False},
            {"quality_title": "SDTV", "preference": "1", "physical_media": False},
            {"quality_title": "HDTV-720p", "preference": "2", "physical_media": False},
            {"quality_title": "HDTV-1080p", "preference": "3", "physical_media": False},
            {"quality_title": "HDTV-2160p", "preference": "4", "physical_media": False},
            {"quality_title": "Raw-HD", "preference": "5", "physical_media": False},
            {"quality_title": "WEBRip-480p", "preference": "6", "physical_media": False},
            {"quality_title": "WEBDL-480p", "preference": "7", "physical_media": False},
            {"quality_title": "DVD", "preference": "8", "physical_media": True},
            {"quality_title": "Bluray-480p", "preference": "9", "physical_media": True},
            {"quality_title": "WEBRip-720p", "preference": "10", "physical_media": False},
            {"quality_title": "WEBDL-720p", "preference": "11", "physical_media": False},
            {"quality_title": "Bluray-720p", "preference": "12", "physical_media": True},
            {"quality_title": "WEBRip-1080p", "preference": "13", "physical_media": False},
            {"quality_title": "WEBDL-1080p", "preference": "14", "physical_media": False},
            {"quality_title": "WEBRip-2160p", "preference": "15", "physical_media": False},
            {"quality_title": "WEBDL-2160p", "preference": "16", "physical_media": False},
            {"quality_title": "Bluray-1080p", "preference": "17", "physical_media": True},
            {"quality_title": "Bluray-1080p Remux", "preference": "18", "physical_media": True},
            {"quality_title": "Bluray-2160p", "preference": "19", "physical_media": True},
            {"quality_title": "Bluray-2160p Remux", "preference": "20", "physical_media": True},
        ],
    )
    op.bulk_insert(
        ref_tmdb_certification,
        [
            {'certification': 'E',
              'country': 'AU',
              'meaning': 'Exempt from classification. Films that are exempt from '
                         'classification must not contain contentious material (i.e. '
                         'material that would ordinarily be rated M or higher).',
              'order': 1},
             {'certification': 'G',
              'country': 'AU',
              'meaning': 'General. The content is very mild in impact.',
              'order': 2},
             {'certification': 'R18+',
              'country': 'AU',
              'meaning': 'Restricted to 18 years and over. Adults only. The content is '
                         'high in impact.',
              'order': 6},
             {'certification': 'RC',
              'country': 'AU',
              'meaning': 'Refused Classification. Banned from sale or hire in Australia; '
                         'also generally applies to importation (if inspected by and '
                         'suspicious to Customs). Private Internet viewing is unenforced '
                         'and attempts to legally censor such online material has resulted '
                         'in controversy. Films are rated RC if their content exceeds the '
                         'guidelines. The content is very high in impact.',
              'order': 8},
             {'certification': 'PG',
              'country': 'AU',
              'meaning': 'Parental guidance recommended. There are no age restrictions. '
                         'The content is mild in impact.',
              'order': 3},
             {'certification': 'M',
              'country': 'AU',
              'meaning': 'Recommended for mature audiences. There are no age restrictions. '
                         'The content is moderate in impact.',
              'order': 4},
             {'certification': 'MA15+',
              'country': 'AU',
              'meaning': 'Mature Accompanied. Unsuitable for children younger than 15. '
                         'Children younger than 15 years must be accompanied by a parent '
                         'or guardian. The content is strong in impact.',
              'order': 5},
             {'certification': 'X18+',
              'country': 'AU',
              'meaning': 'Restricted to 18 years and over. Films with this rating have '
                         'pornographic content. Films classified as X18+ are banned from '
                         'being sold or rented in all Australian states and are only '
                         'legally available in the Australian Capital Territory and the '
                         'Northern Territory. However, importing X18+ material from the '
                         'two territories to any of the Australian states is legal.The '
                         'content is sexually explicit in impact.',
              'order': 7},
             {'certification': 'A',
              'country': 'BG',
              'meaning': 'Recommended for children.',
              'order': 1},
             {'certification': 'B',
              'country': 'BG',
              'meaning': 'Without age restrictions.',
              'order': 2},
             {'certification': 'C',
              'country': 'BG',
              'meaning': 'Not recommended for children under 12.',
              'order': 3},
             {'certification': 'D',
              'country': 'BG',
              'meaning': 'Prohibited for persons under 16.',
              'order': 4},
             {'certification': 'X',
              'country': 'BG',
              'meaning': 'Prohibited for persons under 18.',
              'order': 5},
             {'certification': 'L',
              'country': 'BR',
              'meaning': 'General Audiences. Do not expose children to potentially harmful '
                         'content.',
              'order': 1},
             {'certification': '10',
              'country': 'BR',
              'meaning': 'Not recommended for minors under ten. Violent content or '
                         'inappropriate language to children, even if of a less intensity.',
              'order': 2},
             {'certification': '12',
              'country': 'BR',
              'meaning': 'Not recommended for minors under twelve. Scenes can include '
                         'physical aggression, use of legal drugs and sexual innuendo.',
              'order': 3},
             {'certification': '14',
              'country': 'BR',
              'meaning': 'Not recommended for minors under fourteen. More violent '
                         'material, stronger sex references and/or nudity.',
              'order': 4},
             {'certification': '16',
              'country': 'BR',
              'meaning': 'Not recommended for minors under sixteen. Scenes featuring '
                         'production, trafficking and/or use of illegal drugs, '
                         'hyper-realistic sex, sexual violence, abortion, torture, '
                         'mutilation, suicide, trivialization of violence and death '
                         'penalty.',
              'order': 5},
             {'certification': '18',
              'country': 'BR',
              'meaning': 'Not recommended for minors under eighteen. Scenes featuring '
                         'explicit sex, incest, pedophilia, praising of the use of illegal '
                         'drugs and violence of a strong imagery impact.',
              'order': 6},
             {'certification': '18A',
              'country': 'CA',
              'meaning': 'Persons under 18 years of age must be accompanied by an adult. '
                         'In the Maritimes & Manitoba, children under the age of 14 are '
                         'prohibited from viewing the film.',
              'order': 4},
             {'certification': 'G', 'country': 'CA', 'meaning': 'All ages.', 'order': 1},
             {'certification': 'PG',
              'country': 'CA',
              'meaning': 'Parental guidance advised. There is no age restriction but some '
                         'material may not be suitable for all children.',
              'order': 2},
             {'certification': '14A',
              'country': 'CA',
              'meaning': 'Persons under 14 years of age must be accompanied by an adult.',
              'order': 3},
             {'certification': 'A',
              'country': 'CA',
              'meaning': 'Admittance restricted to people 18 years of age or older. Sole '
                         'purpose of the film is the portrayal of sexually explicit '
                         'activity and/or explicit violence.',
              'order': 5},
             {'certification': 'NR',
              'country': 'CA-QC',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': 'G',
              'country': 'CA-QC',
              'meaning': 'General Rating – May be viewed, rented or purchased by persons '
                         'of all ages. If a film carrying a "G" rating might offend the '
                         'sensibilities of a child under 8 years of age, "Not suitable for '
                         'young children" is appended to the classification.',
              'order': 1},
             {'certification': '13+',
              'country': 'CA-QC',
              'meaning': '13 years and over – May be viewed, rented or purchased only by '
                         'children 13 years of age or over. Children under 13 may be '
                         'admitted only if accompanied by an adult.',
              'order': 2},
             {'certification': '16+',
              'country': 'CA-QC',
              'meaning': '16 years and over – May be viewed, rented or purchased only by '
                         'children 16 years of age or over.',
              'order': 3},
             {'certification': '18+',
              'country': 'CA-QC',
              'meaning': '18 years and over – May be viewed, rented or purchased only by '
                         'adults 18 years of age or over. If a film contains real and '
                         'explicit sexual activity "Explicit sexuality" is appended to the '
                         'classification, and in the retail video industry storeowners are '
                         'required to place the film in a room reserved for adults.',
              'order': 4},
             {'certification': '0',
              'country': 'DE',
              'meaning': 'No age restriction.',
              'order': 1},
             {'certification': '6',
              'country': 'DE',
              'meaning': 'No children younger than 6 years admitted.',
              'order': 2},
             {'certification': '12',
              'country': 'DE',
              'meaning': 'Children 12 or older admitted, children between 6 and 11 only '
                         'when accompanied by parent or a legal guardian.',
              'order': 3},
             {'certification': '16',
              'country': 'DE',
              'meaning': 'Children 16 or older admitted, nobody under this age admitted.',
              'order': 4},
             {'certification': '18',
              'country': 'DE',
              'meaning': 'No youth admitted, only adults.',
              'order': 5},
             {'certification': 'NR',
              'country': 'DK',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': 'A',
              'country': 'DK',
              'meaning': 'Suitable for a general audience.',
              'order': 1},
             {'certification': '7',
              'country': 'DK',
              'meaning': 'Not recommended for children under 7.',
              'order': 2},
             {'certification': '11',
              'country': 'DK',
              'meaning': 'For ages 11 and up.',
              'order': 3},
             {'certification': '15',
              'country': 'DK',
              'meaning': 'For ages 15 and up.',
              'order': 4},
             {'certification': 'F',
              'country': 'DK',
              'meaning': 'Exempt from classification.',
              'order': 5},
             {'certification': 'APTA',
              'country': 'ES',
              'meaning': 'General admission.',
              'order': 1},
             {'certification': '7',
              'country': 'ES',
              'meaning': 'Not recommended for audiences under 7.',
              'order': 2},
             {'certification': '12',
              'country': 'ES',
              'meaning': 'Not recommended for audiences under 12.',
              'order': 3},
             {'certification': '16',
              'country': 'ES',
              'meaning': 'Not recommended for audiences under 16.',
              'order': 4},
             {'certification': '18',
              'country': 'ES',
              'meaning': 'Not recommended for audiences under 18.',
              'order': 5},
             {'certification': 'X',
              'country': 'ES',
              'meaning': 'Prohibited for audiences under 18.',
              'order': 6},
             {'certification': 'S',
              'country': 'FI',
              'meaning': 'For all ages.',
              'order': 1},
             {'certification': 'K-7',
              'country': 'FI',
              'meaning': 'Over 7 years.',
              'order': 2},
             {'certification': 'K-12',
              'country': 'FI',
              'meaning': 'Over 12 years.',
              'order': 3},
             {'certification': 'K-16',
              'country': 'FI',
              'meaning': 'Over 16 years.',
              'order': 4},
             {'certification': 'K-18',
              'country': 'FI',
              'meaning': 'Adults only.',
              'order': 5},
             {'certification': 'KK',
              'country': 'FI',
              'meaning': 'Banned from commercial distribution.',
              'order': 6},
             {'certification': 'U',
              'country': 'FR',
              'meaning': '(Tous publics) valid for all audiences.',
              'order': 1},
             {'certification': '12',
              'country': 'FR',
              'meaning': '(Interdit aux moins de 12 ans) unsuitable for children younger '
                         'than 12 or forbidden in cinemas for under 12.',
              'order': 3},
             {'certification': '10',
              'country': 'FR',
              'meaning': '(Déconseillé aux moins de 10 ans) unsuitable for children '
                         'younger than 10 (this rating is only used for TV); equivalent in '
                         'theatres : "avertissement" (warning), some scenes may be '
                         'disturbing to young children and sensitive people; equivalent on '
                         'video : "accord parental" (parental guidance).',
              'order': 2},
             {'certification': '16',
              'country': 'FR',
              'meaning': '(Interdit aux moins de 16 ans) unsuitable for children younger '
                         'than 16 or forbidden in cinemas for under 16.',
              'order': 4},
             {'certification': '18',
              'country': 'FR',
              'meaning': '(Interdit aux mineurs) unsuitable for children younger than 18 '
                         'or forbidden in cinemas for under 18.',
              'order': 5},
             {'certification': '15',
              'country': 'GB',
              'meaning': 'Only those over 15 years are admitted. Nobody younger than 15 '
                         'can rent or buy a 15-rated VHS, DVD, Blu-ray Disc, UMD or game, '
                         'or watch a film in the cinema with this rating. Films under this '
                         'category can contain adult themes, hard drugs, frequent strong '
                         'language and limited use of very strong language, strong '
                         'violence and strong sex references, and nudity without graphic '
                         'detail. Sexual activity may be portrayed but without any strong '
                         'detail. Sexual violence may be shown if discreet and justified '
                         'by context.',
              'order': 5},
             {'certification': 'R18',
              'country': 'GB',
              'meaning': 'Can only be shown at licensed adult cinemas or sold at licensed '
                         'sex shops, and only to adults, those aged 18 or over. Films '
                         'under this category are always hard-core pornography, defined as '
                         'material intended for sexual stimulation and containing clear '
                         'images of real sexual activity, strong fetish material, explicit '
                         'animated images, or sight of certain acts such as triple '
                         'simultaneous penetration and snowballing. There remains a range '
                         'of material that is often cut from the R18 rating: strong images '
                         'of injury in BDSM or spanking works, urolagnia, scenes '
                         'suggesting incest even if staged, references to underage sex or '
                         'childhood sexual development and aggressive behaviour such as '
                         'hair-pulling or spitting on a performer are not permitted. More '
                         'cuts are demanded in this category than any other category.',
              'order': 7},
             {'certification': 'U',
              'country': 'GB',
              'meaning': 'All ages admitted, there is nothing unsuitable for children.',
              'order': 1},
             {'certification': 'PG',
              'country': 'GB',
              'meaning': 'All ages admitted, but certain scenes may be unsuitable for '
                         'young children. May contain mild language and sex/drugs '
                         'references. May contain moderate violence if justified by '
                         'context (e.g. fantasy).',
              'order': 2},
             {'certification': '12A',
              'country': 'GB',
              'meaning': 'Films under this category are considered to be unsuitable for '
                         'very young people. Those aged under 12 years are only admitted '
                         'if accompanied by an adult, aged at least 18 years, at all times '
                         'during the motion picture. However, it is generally not '
                         'recommended that children under 12 years should watch the film. '
                         'Films under this category can contain mature themes, '
                         'discrimination, soft drugs, moderate swear words, infrequent '
                         'strong language and moderate violence, sex references and '
                         'nudity. Sexual activity may be briefly and discreetly portrayed. '
                         'Sexual violence may be implied or briefly indicated.',
              'order': 3},
             {'certification': '12',
              'country': 'GB',
              'meaning': 'Home media only since 2002. 12A-rated films are usually given a '
                         '12 certificate for the VHS/DVD version unless extra material has '
                         'been added that requires a higher rating. Nobody younger than 12 '
                         'can rent or buy a 12-rated VHS, DVD, Blu-ray Disc, UMD or game. '
                         'The content guidelines are identical to those used for the 12A '
                         'certificate.',
              'order': 4},
             {'certification': '18',
              'country': 'GB',
              'meaning': 'Only adults are admitted. Nobody younger than 18 can rent or buy '
                         'an 18-rated VHS, DVD, Blu-ray Disc, UMD or game, or watch a film '
                         'in the cinema with this rating. Films under this category do not '
                         'have limitation on the bad language that is used. Hard drugs are '
                         'generally allowed, and explicit sex references along with '
                         'detailed sexual activity are also allowed. Scenes of strong real '
                         'sex may be permitted if justified by the context. Very strong, '
                         'gory, and/or sadistic violence is usually permitted. Strong '
                         'sexual violence is permitted unless it is eroticised or '
                         'excessively graphic.',
              'order': 6},
             {'certification': 'NR',
              'country': 'HU',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': 'KN',
              'country': 'HU',
              'meaning': 'Without age restriction.',
              'order': 1},
             {'certification': '6',
              'country': 'HU',
              'meaning': 'Not recommended below age of 6.',
              'order': 2},
             {'certification': '12',
              'country': 'HU',
              'meaning': 'Not recommended below age of 12.',
              'order': 3},
             {'certification': '16',
              'country': 'HU',
              'meaning': 'Not recommended below age of 16.',
              'order': 4},
             {'certification': '18',
              'country': 'HU',
              'meaning': 'Not recommended below age of 18.',
              'order': 5},
             {'certification': 'X',
              'country': 'HU',
              'meaning': 'Restricted below 18, for adults only.',
              'order': 6},
             {'certification': 'U',
              'country': 'IN',
              'meaning': 'Unrestricted Public Exhibition throughout India, suitable for '
                         'all age groups. Films under this category should not upset '
                         'children over 4. Such films may contain educational, social or '
                         'family-oriented themes. Films under this category may also '
                         'contain fantasy violence and/or mild bad language.',
              'order': 0},
             {'certification': 'UA',
              'country': 'IN',
              'meaning': 'All ages admitted, but it is advised that children below 12 be '
                         'accompanied by a parent as the theme or content may be '
                         'considered intense or inappropriate for young children. Films '
                         'under this category may contain mature themes, sexual '
                         'references, mild sex scenes, violence with brief gory images '
                         'and/or infrequent use of crude language.',
              'order': 1},
             {'certification': 'A',
              'country': 'IN',
              'meaning': 'Restricted to adult audiences (18 years or over). Nobody below '
                         'the age of 18 may buy/rent an A-rated DVD, VHS, UMD or watch a '
                         'film in the cinema with this rating. Films under this category '
                         'may contain adult/disturbing themes, frequent crude language, '
                         'brutal violence with blood and gore, strong sex scenes and/or '
                         'scenes of drug abuse which is considered unsuitable for minors.',
              'order': 2},
             {'certification': 'NR',
              'country': 'IT',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': 'T',
              'country': 'IT',
              'meaning': 'All ages admitted.',
              'order': 1},
             {'certification': 'VM14',
              'country': 'IT',
              'meaning': 'No admittance for children under 14.',
              'order': 2},
             {'certification': 'VM18',
              'country': 'IT',
              'meaning': 'No admittance for children under 18.',
              'order': 3},
             {'certification': 'NR',
              'country': 'LT',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': 'V',
              'country': 'LT',
              'meaning': 'Movies for the audience of all ages.',
              'order': 1},
             {'certification': 'N-7',
              'country': 'LT',
              'meaning': 'Movies for viewers from 7 years old. Younger than 7 years of '
                         'age, viewers of this index have been featured only together with '
                         'accompanying adult persons.',
              'order': 2},
             {'certification': 'N-13',
              'country': 'LT',
              'meaning': 'Movies for viewers from 13 years of age. The viewers from 7 to '
                         '13 years of age are allowed to enter this index only together '
                         'with accompanying adult persons.',
              'order': 3},
             {'certification': 'N-16',
              'country': 'LT',
              'meaning': 'Movies for viewers from 16 years of age.',
              'order': 4},
             {'certification': 'N-18',
              'country': 'LT',
              'meaning': 'Movies for viewers from 18 years of age.',
              'order': 5},
             {'certification': 'NR',
              'country': 'MY',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': 'U',
              'country': 'MY',
              'meaning': '(Umum: "General Audiences") - For general audiences. (Used by '
                         'the majority of films screened in Malaysia until 2008 but it '
                         'continues only for television, notably for RTM.)',
              'order': 1},
             {'certification': 'P13',
              'country': 'MY',
              'meaning': '(Penjaga 13 : "Parental Guidance 13") - Children under 13 not '
                         'admitted unless accompanied by an adult. (Introduced in 2006, '
                         'this became the official Malaysian motion picture rating system '
                         'in 2008. The "PG-13" rating was revised to "P13" from April 2012 '
                         'onwards to emphasize the use of Malay language instead of '
                         'English.) Passionate kissing scenes are not allowed under a P13 '
                         'rating.',
              'order': 2},
             {'certification': '18SG',
              'country': 'MY',
              'meaning': '(Seram, Ganas: "Graphic Violence and Horror/Terror") - Film may '
                         'contain strong violence, gore or horror/terror people may find '
                         'objectionable.',
              'order': 3},
             {'certification': '18SX',
              'country': 'MY',
              'meaning': '(Seks: "Sexual Content") - Film may contain sex scenes, nudity '
                         'or sexual dialogue/references people may find objectionable '
                         '(despite scenes of sex and nudity being strictly censored off by '
                         'the LPF.)',
              'order': 4},
             {'certification': '18PA',
              'country': 'MY',
              'meaning': '(Politik, Agama: "Strong Religious or Political Elements") - '
                         'Film may contain elements which include religious, social or '
                         'political aspects people may find objectionable. Rarely used.',
              'order': 5},
             {'certification': '18PL',
              'country': 'MY',
              'meaning': '(Pelbagai: "Various") - Film may contain strong violence, gore, '
                         'horror/terror, sex scenes, nudity, sexual dialogues/references, '
                         'religious, social or political aspects people may find '
                         'objectionable. The majority of the 18+ movies use this rating. '
                         'For example, a film with sex scenes and strong violence will be '
                         'classified as 18PL, despite scenes of sex and nudity being '
                         'strictly censored off by the LPF.',
              'order': 6},
             {'certification': 'AL', 'country': 'NL', 'meaning': 'All ages.', 'order': 1},
             {'certification': '6',
              'country': 'NL',
              'meaning': 'Potentially harmful to children under 6 years.',
              'order': 2},
             {'certification': '9',
              'country': 'NL',
              'meaning': 'Potentially harmful to children under 9 years.',
              'order': 3},
             {'certification': '12',
              'country': 'NL',
              'meaning': 'Potentially harmful to children under 12 years; broadcasting is '
                         'not allowed before 8:00 pm.',
              'order': 4},
             {'certification': '16',
              'country': 'NL',
              'meaning': 'Potentially harmful to children under 16 years; broadcasting is '
                         'not allowed before 10:00 pm.',
              'order': 5},
             {'certification': 'NR',
              'country': 'NO',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': 'A',
              'country': 'NO',
              'meaning': 'Suitable for all.',
              'order': 1},
             {'certification': '6',
              'country': 'NO',
              'meaning': '6 years (no restriction for children accompanied by an adult).',
              'order': 2},
             {'certification': '9',
              'country': 'NO',
              'meaning': '9 years (children down to 6 years accompanied by an adult).',
              'order': 3},
             {'certification': '12',
              'country': 'NO',
              'meaning': '12 years (children down to 9 years accompanied by an adult).',
              'order': 4},
             {'certification': '15',
              'country': 'NO',
              'meaning': '15 years (young down to 12 years accompanied by an adult).',
              'order': 5},
             {'certification': '18',
              'country': 'NO',
              'meaning': ' 18 years (absolute lower limit).',
              'order': 6},
             {'certification': 'M',
              'country': 'NZ',
              'meaning': 'Suitable for (but not restricted to) mature audiences 16 years '
                         'and up.',
              'order': 3},
             {'certification': '13',
              'country': 'NZ',
              'meaning': 'Restricted to persons 13 years of age and over.',
              'order': 4},
             {'certification': '15',
              'country': 'NZ',
              'meaning': 'Restricted to persons 15 years of age and over.',
              'order': 5},
             {'certification': 'G',
              'country': 'NZ',
              'meaning': 'Suitable for general audiences.',
              'order': 1},
             {'certification': 'PG',
              'country': 'NZ',
              'meaning': 'Parental guidance recommended for younger viewers.',
              'order': 2},
             {'certification': '16',
              'country': 'NZ',
              'meaning': 'Restricted to persons 16 years of age and over.',
              'order': 6},
             {'certification': '18',
              'country': 'NZ',
              'meaning': 'Restricted to persons 18 years of age and over.',
              'order': 7},
             {'certification': 'R',
              'country': 'NZ',
              'meaning': 'Restricted to a particular class of persons, or for particular '
                         'purposes, or both.',
              'order': 8},
             {'certification': 'NR',
              'country': 'PH',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': 'G',
              'country': 'PH',
              'meaning': 'Viewers of all ages are admitted.',
              'order': 1},
             {'certification': 'PG',
              'country': 'PH',
              'meaning': 'Viewers below 13 years old must be accompanied by a parent or '
                         'supervising adult.',
              'order': 2},
             {'certification': 'R-13',
              'country': 'PH',
              'meaning': 'Only viewers who are 13 years old and above can be admitted.',
              'order': 3},
             {'certification': 'R-16',
              'country': 'PH',
              'meaning': 'Only viewers who are 16 years old and above can be admitted.',
              'order': 4},
             {'certification': 'R-18',
              'country': 'PH',
              'meaning': 'Only viewers who are 18 years old and above can be admitted.',
              'order': 5},
             {'certification': 'X',
              'country': 'PH',
              'meaning': '“X-rated” films are not suitable for public exhibition.',
              'order': 6},
             {'certification': 'Públicos',
              'country': 'PT',
              'meaning': 'For all the public (especially designed for children under 3 '
                         'years of age).',
              'order': 1},
             {'certification': 'M/3',
              'country': 'PT',
              'meaning': 'Passed for viewers aged 3 and older.',
              'order': 2},
             {'certification': 'M/6',
              'country': 'PT',
              'meaning': 'Passed for viewers aged 6 and older.',
              'order': 3},
             {'certification': 'M/12',
              'country': 'PT',
              'meaning': 'Passed for viewers aged 12 and older.',
              'order': 4},
             {'certification': 'M/14',
              'country': 'PT',
              'meaning': 'Passed for viewers aged 14 and older.',
              'order': 5},
             {'certification': 'M/16',
              'country': 'PT',
              'meaning': 'Passed for viewers aged 16 and older.',
              'order': 6},
             {'certification': 'M/18',
              'country': 'PT',
              'meaning': 'Passed for viewers aged 18 and older.',
              'order': 7},
             {'certification': 'P',
              'country': 'PT',
              'meaning': 'Special rating supplementary to the M/18 age rating denoting '
                         'pornography.',
              'order': 8},
             {'certification': 'NR',
              'country': 'RU',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': '0+',
              'country': 'RU',
              'meaning': 'All ages are admitted.',
              'order': 1},
             {'certification': '6+',
              'country': 'RU',
              'meaning': '(For children above 6) – Unsuitable for children under 6.',
              'order': 2},
             {'certification': '12+',
              'country': 'RU',
              'meaning': '(For children above 12) – Unsuitable for children under 12.',
              'order': 3},
             {'certification': '16+',
              'country': 'RU',
              'meaning': '(For children above 16) – Unsuitable for children under 16.',
              'order': 4},
             {'certification': '18+',
              'country': 'RU',
              'meaning': '(Prohibited for children) – Prohibited for children under 18.',
              'order': 5},
             {'certification': 'NR',
              'country': 'SE',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': 'Btl', 'country': 'SE', 'meaning': 'All ages.', 'order': 1},
             {'certification': '7',
              'country': 'SE',
              'meaning': 'Children under the age of 7, who are accompanied by an adult (a '
                         'person aged 18 or over), are admitted to films that have been '
                         'passed for children from the age of 7.',
              'order': 2},
             {'certification': '11',
              'country': 'SE',
              'meaning': 'Children over the age of 7, who are accompanied by an adult, are '
                         'admitted to films that have been passed for children from the '
                         'age of 11.',
              'order': 3},
             {'certification': '15',
              'country': 'SE',
              'meaning': 'Children over the age of 7, who are accompanied by an adult, are '
                         'admitted to films that have been passed for children from the '
                         'age of 11. Updated on March 1, 2017.',
              'order': 4},
             {'certification': 'G',
              'country': 'US',
              'meaning': 'All ages admitted. There is no content that would be '
                         'objectionable to most parents. This is one of only two ratings '
                         'dating back to 1968 that still exists today.',
              'order': 1},
             {'certification': 'PG-13',
              'country': 'US',
              'meaning': 'Some material may be inappropriate for children under 13. Films '
                         'given this rating may contain sexual content, brief or partial '
                         'nudity, some strong language and innuendo, humor, mature themes, '
                         'political themes, terror and/or intense action violence. '
                         'However, bloodshed is rarely present. This is the minimum rating '
                         'at which drug content is present.',
              'order': 3},
             {'certification': 'R',
              'country': 'US',
              'meaning': 'Under 17 requires accompanying parent or adult guardian 21 or '
                         'older. The parent/guardian is required to stay with the child '
                         'under 17 through the entire movie, even if the parent gives the '
                         'child/teenager permission to see the film alone. These films may '
                         'contain strong profanity, graphic sexuality, nudity, strong '
                         'violence, horror, gore, and strong drug use. A movie rated R for '
                         'profanity often has more severe or frequent language than the '
                         'PG-13 rating would permit. An R-rated movie may have more blood, '
                         'gore, drug use, nudity, or graphic sexuality than a PG-13 movie '
                         'would admit.',
              'order': 4},
             {'certification': 'NC-17',
              'country': 'US',
              'meaning': 'These films contain excessive graphic violence, intense or '
                         'explicit sex, depraved, abhorrent behavior, explicit drug abuse, '
                         'strong language, explicit nudity, or any other elements which, '
                         'at present, most parents would consider too strong and therefore '
                         'off-limits for viewing by their children and teens. NC-17 does '
                         'not necessarily mean obscene or pornographic in the oft-accepted '
                         'or legal meaning of those words.',
              'order': 5},
             {'certification': 'NR',
              'country': 'US',
              'meaning': 'No rating information.',
              'order': 0},
             {'certification': 'PG',
              'country': 'US',
              'meaning': 'Some material may not be suitable for children under 10. These '
                         'films may contain some mild language, crude/suggestive humor, '
                         'scary moments and/or violence. No drug content is present. There '
                         'are a few exceptions to this rule. A few racial insults may also '
                         'be heard.',
              'order': 2}
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_subtitle_track')
    op.drop_table('file_audio_track')
    op.drop_table('user_movie_review')
    op.drop_table('tv_seasons')
    op.drop_table('tv_production_companies')
    op.drop_table('tv_networks')
    op.drop_table('tv_keywords')
    op.drop_table('tv_genres')
    op.drop_table('tv_crew')
    op.drop_table('tv_cast')
    op.drop_table('movie_spoken_languages')
    op.drop_table('movie_production_countries')
    op.drop_table('movie_production_companies')
    op.drop_table('movie_keywords')
    op.drop_table('movie_genres')
    op.drop_table('movie_crew')
    op.drop_table('movie_collections')
    op.drop_table('movie_certifications')
    op.drop_table('movie_cast')
    op.drop_index(op.f('ix_file_version'), table_name='file')
    op.drop_index(op.f('ix_file_plex_title'), table_name='file')
    op.drop_index(op.f('ix_file_media_library'), table_name='file')
    op.drop_index(op.f('ix_file_fullscreen'), table_name='file')
    op.drop_index(op.f('ix_file_file_path'), table_name='file')
    op.drop_index(op.f('ix_file_date_updated'), table_name='file')
    op.drop_index(op.f('ix_file_date_transcoded'), table_name='file')
    op.drop_index(op.f('ix_file_date_localized'), table_name='file')
    op.drop_index(op.f('ix_file_date_archived'), table_name='file')
    op.drop_index(op.f('ix_file_date_added'), table_name='file')
    op.drop_index(op.f('ix_file_aws_untouched_key'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tv_series_title'), table_name='tv_series')
    op.drop_index(op.f('ix_tv_series_date_updated'), table_name='tv_series')
    op.drop_index(op.f('ix_tv_series_date_created'), table_name='tv_series')
    op.drop_table('tv_series')
    op.drop_table('tmdb_spoken_language')
    op.drop_table('tmdb_season')
    op.drop_table('tmdb_production_country')
    op.drop_table('tmdb_production_company')
    op.drop_table('tmdb_network')
    op.drop_table('tmdb_movie_collection')
    op.drop_table('tmdb_keyword')
    op.drop_table('tmdb_genre')
    op.drop_table('tmdb_credit')
    op.drop_table('ref_tmdb_certification')
    op.drop_table('ref_quality')
    op.drop_table('ref_feature_type')
    op.drop_index(op.f('ix_movie_year'), table_name='movie')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_date_updated'), table_name='movie')
    op.drop_index(op.f('ix_movie_date_created'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
