"""empty message

Revision ID: 365fc2fbc722
Revises: 7c0da861a217
Create Date: 2023-05-18 13:39:02.713046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365fc2fbc722'
down_revision = '7c0da861a217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_subtitle_track', sa.Column('compression_mode', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_subtitle_track', 'compression_mode')
    # ### end Alembic commands ###
