"""Add AWS uploaded filesize column

Revision ID: 36633535d4ce
Revises: 4a34ba4d069f
Create Date: 2026-08-04 20:53:07.178098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36633535d4ce'
down_revision = '4a34ba4d069f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aws_untouched_filesize', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('aws_untouched_filesize')

    # ### end Alembic commands ###
