"""user movie status flags

Revision ID: 3a26bd38a0d1
Revises: b0ff7e7f4ec6
Create Date: 2026-08-12 23:42:17.936764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a26bd38a0d1'
down_revision = 'b0ff7e7f4ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_movie_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', 'kind')
    )
    with op.batch_alter_table('user_movie_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_movie_status_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_movie_status_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_movie_status_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_movie_status_movie_id'))

    op.drop_table('user_movie_status')
    # ### end Alembic commands ###
