"""empty message

Revision ID: 3fe276df07b6
Revises: 1e5fcf53ec93
Create Date: 2024-04-02 23:30:18.452077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe276df07b6'
down_revision = '1e5fcf53ec93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('custom_poster', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'custom_poster')
    # ### end Alembic commands ###
