"""empty message

Revision ID: 40b018e83e16
Revises: 3fe276df07b6
Create Date: 2024-10-23 14:53:44.973946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b018e83e16'
down_revision = '3fe276df07b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'file', 'tv_series', ['series_id'], ['id'])
    op.create_foreign_key(None, 'file', 'ref_feature_type', ['feature_type_id'], ['id'])
    op.create_foreign_key(None, 'file', 'ref_quality', ['quality_id'], ['id'])
    op.create_foreign_key(None, 'file', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'file_audio_track', 'file', ['file_id'], ['id'])
    op.create_foreign_key(None, 'file_subtitle_track', 'file', ['file_id'], ['id'])
    op.add_column('movie', sa.Column('criterion_quality', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movie', 'ref_quality', ['criterion_quality'], ['id'])
    op.create_foreign_key(None, 'movie_cast', 'tmdb_credit', ['credit_id'], ['id'])
    op.create_foreign_key(None, 'movie_cast', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'movie_certifications', 'ref_tmdb_certification', ['certification_id'], ['id'])
    op.create_foreign_key(None, 'movie_certifications', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'movie_collections', 'tmdb_movie_collection', ['collection_id'], ['id'])
    op.create_foreign_key(None, 'movie_collections', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'movie_crew', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'movie_crew', 'tmdb_credit', ['credit_id'], ['id'])
    op.create_foreign_key(None, 'movie_genres', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'movie_genres', 'tmdb_genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'movie_keywords', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'movie_keywords', 'tmdb_keyword', ['keyword_id'], ['id'])
    op.create_foreign_key(None, 'movie_production_companies', 'tmdb_production_company', ['company_id'], ['id'])
    op.create_foreign_key(None, 'movie_production_companies', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'movie_production_countries', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'movie_production_countries', 'tmdb_production_country', ['country_id'], ['id'])
    op.create_foreign_key(None, 'movie_spoken_languages', 'tmdb_spoken_language', ['country_id'], ['id'])
    op.create_foreign_key(None, 'movie_spoken_languages', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'tv_cast', 'tv_series', ['tv_id'], ['id'])
    op.create_foreign_key(None, 'tv_cast', 'tmdb_credit', ['credit_id'], ['id'])
    op.create_foreign_key(None, 'tv_crew', 'tv_series', ['tv_id'], ['id'])
    op.create_foreign_key(None, 'tv_crew', 'tmdb_credit', ['credit_id'], ['id'])
    op.create_foreign_key(None, 'tv_genres', 'tmdb_genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'tv_genres', 'tv_series', ['tv_id'], ['id'])
    op.create_foreign_key(None, 'tv_keywords', 'tv_series', ['tv_id'], ['id'])
    op.create_foreign_key(None, 'tv_keywords', 'tmdb_keyword', ['keyword_id'], ['id'])
    op.create_foreign_key(None, 'tv_networks', 'tv_series', ['tv_id'], ['id'])
    op.create_foreign_key(None, 'tv_networks', 'tmdb_network', ['network_id'], ['id'])
    op.create_foreign_key(None, 'tv_production_companies', 'tmdb_production_company', ['company_id'], ['id'])
    op.create_foreign_key(None, 'tv_production_companies', 'tv_series', ['tv_id'], ['id'])
    op.create_foreign_key(None, 'tv_seasons', 'tv_series', ['tv_id'], ['id'])
    op.create_foreign_key(None, 'tv_seasons', 'tmdb_season', ['season_id'], ['id'])
    op.create_foreign_key(None, 'user_movie_review', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'user_movie_review', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_movie_review', type_='foreignkey')
    op.drop_constraint(None, 'user_movie_review', type_='foreignkey')
    op.drop_constraint(None, 'tv_seasons', type_='foreignkey')
    op.drop_constraint(None, 'tv_seasons', type_='foreignkey')
    op.drop_constraint(None, 'tv_production_companies', type_='foreignkey')
    op.drop_constraint(None, 'tv_production_companies', type_='foreignkey')
    op.drop_constraint(None, 'tv_networks', type_='foreignkey')
    op.drop_constraint(None, 'tv_networks', type_='foreignkey')
    op.drop_constraint(None, 'tv_keywords', type_='foreignkey')
    op.drop_constraint(None, 'tv_keywords', type_='foreignkey')
    op.drop_constraint(None, 'tv_genres', type_='foreignkey')
    op.drop_constraint(None, 'tv_genres', type_='foreignkey')
    op.drop_constraint(None, 'tv_crew', type_='foreignkey')
    op.drop_constraint(None, 'tv_crew', type_='foreignkey')
    op.drop_constraint(None, 'tv_cast', type_='foreignkey')
    op.drop_constraint(None, 'tv_cast', type_='foreignkey')
    op.drop_constraint(None, 'movie_spoken_languages', type_='foreignkey')
    op.drop_constraint(None, 'movie_spoken_languages', type_='foreignkey')
    op.drop_constraint(None, 'movie_production_countries', type_='foreignkey')
    op.drop_constraint(None, 'movie_production_countries', type_='foreignkey')
    op.drop_constraint(None, 'movie_production_companies', type_='foreignkey')
    op.drop_constraint(None, 'movie_production_companies', type_='foreignkey')
    op.drop_constraint(None, 'movie_keywords', type_='foreignkey')
    op.drop_constraint(None, 'movie_keywords', type_='foreignkey')
    op.drop_constraint(None, 'movie_genres', type_='foreignkey')
    op.drop_constraint(None, 'movie_genres', type_='foreignkey')
    op.drop_constraint(None, 'movie_crew', type_='foreignkey')
    op.drop_constraint(None, 'movie_crew', type_='foreignkey')
    op.drop_constraint(None, 'movie_collections', type_='foreignkey')
    op.drop_constraint(None, 'movie_collections', type_='foreignkey')
    op.drop_constraint(None, 'movie_certifications', type_='foreignkey')
    op.drop_constraint(None, 'movie_certifications', type_='foreignkey')
    op.drop_constraint(None, 'movie_cast', type_='foreignkey')
    op.drop_constraint(None, 'movie_cast', type_='foreignkey')
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_column('movie', 'criterion_quality')
    op.drop_constraint(None, 'file_subtitle_track', type_='foreignkey')
    op.drop_constraint(None, 'file_audio_track', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    # ### end Alembic commands ###
