"""empty message

Revision ID: 526c42e81920
Revises: a21f56500b56
Create Date: 2023-05-15 17:58:37.066375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526c42e81920'
down_revision = 'a21f56500b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_audio_track', sa.Column('codec', sa.String(length=64), nullable=True))
    op.add_column('file_audio_track', sa.Column('bitrate', sa.Integer(), nullable=True))
    op.add_column('file_audio_track', sa.Column('bitrate_kbps', sa.Integer(), nullable=True))
    op.add_column('file_audio_track', sa.Column('bit_depth', sa.Integer(), nullable=True))
    op.add_column('file_audio_track', sa.Column('sampling_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_audio_track', 'sampling_rate')
    op.drop_column('file_audio_track', 'bit_depth')
    op.drop_column('file_audio_track', 'bitrate_kbps')
    op.drop_column('file_audio_track', 'bitrate')
    op.drop_column('file_audio_track', 'codec')
    # ### end Alembic commands ###
