"""empty message

Revision ID: 5ac52e94ca9b
Revises: aae440a32b5d
Create Date: 2025-11-19 14:20:20.292032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac52e94ca9b'
down_revision = 'aae440a32b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('shopping_cart_add_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'shopping_cart_add_date')
    # ### end Alembic commands ###
