"""file runtime_mismatch_reviewed

Revision ID: 5c3032dcb331
Revises: c8e15a2d4f37
Create Date: 2026-08-26 16:40:31.059293

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5c3032dcb331"
down_revision = "c8e15a2d4f37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("runtime_mismatch_reviewed", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_column("runtime_mismatch_reviewed")

    # ### end Alembic commands ###
