"""Add Criterion film id column

Revision ID: 662e5b76b333
Revises: d95fe201f049
Create Date: 2026-08-05 14:02:15.315162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662e5b76b333'
down_revision = 'd95fe201f049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criterion_film_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('criterion_film_id')

    # ### end Alembic commands ###
