"""Add review export bookkeeping to user

Revision ID: 69a4438de2c9
Revises: e4a8b62c9d15
Create Date: 2026-08-10 18:05:07.843611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a4438de2c9'
down_revision = 'e4a8b62c9d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_reviews_exported', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_export_review_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_export_review_id')
        batch_op.drop_column('date_reviews_exported')

    # ### end Alembic commands ###
