"""Added video bitrate column

Revision ID: 6f73088a9bc5
Revises: 2b45991751fb
Create Date: 2020-09-21 11:08:22.839173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f73088a9bc5'
down_revision = '2b45991751fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('video_bitrate_kbps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'video_bitrate_kbps')
    # ### end Alembic commands ###
