"""Add shopping list exclusion column

Revision ID: 76dac814b569
Revises: 6f73088a9bc5
Create Date: 2021-04-06 20:55:46.385958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dac814b569'
down_revision = '6f73088a9bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('shopping_list_exclude', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'shopping_list_exclude')
    # ### end Alembic commands ###
