"""empty message

Revision ID: 7c0da861a217
Revises: 526c42e81920
Create Date: 2023-05-18 13:05:47.684744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c0da861a217'
down_revision = '526c42e81920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_audio_track', sa.Column('sampling_rate_khz', sa.Integer(), nullable=True))
    op.add_column('file_audio_track', sa.Column('language_name', sa.String(length=64), nullable=False))
    op.alter_column('file_audio_track', 'streamorder',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('file_subtitle_track', sa.Column('language_name', sa.String(length=64), nullable=False))
    op.alter_column('file_subtitle_track', 'streamorder',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_subtitle_track', 'streamorder',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('file_subtitle_track', 'language_name')
    op.alter_column('file_audio_track', 'streamorder',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('file_audio_track', 'language_name')
    op.drop_column('file_audio_track', 'sampling_rate_khz')
    # ### end Alembic commands ###
