"""empty message

Revision ID: aae440a32b5d
Revises: 00d8777aab1e
Create Date: 2024-12-08 10:54:24.935242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae440a32b5d'
down_revision = '00d8777aab1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('hdr_format', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'hdr_format')
    # ### end Alembic commands ###
