"""Remove unused date_archived column

Revision ID: c40b0ea1f5c4
Revises: cb2dfffb5e07
Create Date: 2026-07-31 11:00:34.065660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c40b0ea1f5c4'
down_revision = 'cb2dfffb5e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_date_archived', table_name='file')
    op.drop_column('file', 'date_archived')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('date_archived', mysql.DATETIME(), nullable=True))
    op.create_index('ix_file_date_archived', 'file', ['date_archived'], unique=False)
    # ### end Alembic commands ###
