"""empty message

Revision ID: cb2dfffb5e07
Revises: 5ac52e94ca9b
Create Date: 2025-11-19 14:38:58.300840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2dfffb5e07'
down_revision = '5ac52e94ca9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('shopping_cart_priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'shopping_cart_priority')
    # ### end Alembic commands ###
