"""empty message

Revision ID: d568c66a57fa
Revises: d5f58bdea78b
Create Date: 2024-04-02 20:24:09.941580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd568c66a57fa'
down_revision = 'd5f58bdea78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('custom_poster_path', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'custom_poster_path')
    # ### end Alembic commands ###
