"""Rename uploaded filesize column

Revision ID: d95fe201f049
Revises: 36633535d4ce
Create Date: 2026-08-04 21:11:06.437538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd95fe201f049'
down_revision = '36633535d4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aws_untouched_filesize_bytes', sa.BigInteger(), nullable=True))
        batch_op.drop_column('aws_untouched_filesize')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aws_untouched_filesize', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
        batch_op.drop_column('aws_untouched_filesize_bytes')

    # ### end Alembic commands ###
