"""empty message

Revision ID: e62eda6d27de
Revises: b13f4949f47e
Create Date: 2023-12-20 22:14:57.124703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62eda6d27de'
down_revision = 'b13f4949f47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('filesize_megabytes', sa.Numeric(precision=8, scale=1), nullable=True))
    op.add_column('file', sa.Column('filesize_gigabytes', sa.Numeric(precision=5, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'filesize_gigabytes')
    op.drop_column('file', 'filesize_megabytes')
    # ### end Alembic commands ###
