"""movie award table

Revision ID: ec2378b788f2
Revises: 76e7ccfe9e18
Create Date: 2026-08-12 12:23:54.590582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2378b788f2'
down_revision = '76e7ccfe9e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.String(length=32), nullable=True),
    sa.Column('award_name', sa.String(length=512), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'award_id', 'win', 'year')
    )
    with op.batch_alter_table('movie_award', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_award_movie_id'), ['movie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_award', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_award_movie_id'))

    op.drop_table('movie_award')
    # ### end Alembic commands ###
