"""movie_copref similarity table

Revision ID: f83c002588f9
Revises: ec2378b788f2
Create Date: 2026-08-12 21:46:30.230040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83c002588f9'
down_revision = 'ec2378b788f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_copref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id_a', sa.Integer(), nullable=False),
    sa.Column('tmdb_id_b', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id_a', 'tmdb_id_b')
    )
    with op.batch_alter_table('movie_copref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_copref_tmdb_id_a'), ['tmdb_id_a'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_copref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_copref_tmdb_id_a'))

    op.drop_table('movie_copref')
    # ### end Alembic commands ###
