"""TV series carry a US content rating

Revision ID: f943111a60ed
Revises: e5b7c92a41d8
Create Date: 2026-08-31 12:02:38.488353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f943111a60ed'
down_revision = 'e5b7c92a41d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_content_rating', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_series', schema=None) as batch_op:
        batch_op.drop_column('tmdb_content_rating')

    # ### end Alembic commands ###
