"""Add liked flag and allow unrated movie reviews

Revision ID: fee519875a05
Revises: 662e5b76b333
Create Date: 2026-08-05 20:53:41.244761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fee519875a05'
down_revision = '662e5b76b333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('rating',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('modified_rating',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('whole_stars',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('half_stars',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie_review', schema=None) as batch_op:
        batch_op.alter_column('half_stars',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('whole_stars',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('modified_rating',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.drop_column('liked')

    # ### end Alembic commands ###
